# Site settings
title: "Test Site GHP"
url: "https://samuraiblood2.github.io"
permalink: /:title/

# Markdown
markdown: kramdown
highlighter: rouge
kramdown:
	input: GFM
	hard_wrap: false

sass:
	style: compressed

# Gem settings
gems:
	- jekyll-sitemap

exclude:
	- README.MD
