# Site settings
title: "Test Site GHP"
name: "Empty Company"
images: "./assets/images"
url: "https://samuraiblood2.github.io"
permalink: /:title/
encoding: UTF-8

# Markdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false

sass:
  style: compressed

exclude:
  - README.MD
