# Site settings
title: "Test Site GHP"
name: Samurai
description: Testing shit, because theres nothing else to do at 6:00 in the morning.
images: "./assets/images/"
url: "https://samuraiblood2.github.io"
permalink: /:title/
encoding: UTF-8

# Markdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false

sass:
  style: compressed

# Gem settings
gems:
  - jekyll-sitemap

exclude:
  - README.MD
